server:
  port: 86
  servlet:
    context-path: /bpm-service
    session:
      timeout: 480m

logging:
  file:
    path: d:/logs/bpm-service
    name: d:/logs/bpm-service/bpm-service.log
  level:
    root: INFO
    com:
      mt: debug
    

### 人員資料庫連線設定 ###
### 人員資料庫連線設定 ###
app:
  datasource:
    username: sa
    password: password
    jdbc-url: jdbc:h2:file:d:\\h2\\home\\app;INIT=RUNSCRIPT FROM 'src/main/resources/sql/db-init.sql';
    driver-class-name: org.h2.Driver

### Hibernate 屬性設定 ###
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    format_sql: true
    show_sql: true
    
spring:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  sql:
    init:
      mode: ALWAYS
      # schema-locations:
      # - classpath:/sql/schema-test.sql
      # data-locations:      
      # - classpath:sql/data.sql